input: ../Experiment/network_input
parameter_dir: ../Experiment/network_parameters
cupy: 0
params:
  Hybrid:
    lr: 0.00005
    gamma: 0.15
    num_epoch: 50
    lr_steps: [20,40]
    momentum: 0.9
    batchsize: 256
  RF:
    n_estimators: 50
    max_depth: 10
train_models:
  Hybrid_BN_A: 1
  RF: 0
  RBF_SVM: 0
  CNN2D: 0
  CNN3D: 0

